import { motion } from 'framer-motion';
import { Lightbulb, Loader2 } from 'lucide-react';
import { QuarterlyCommentary as CommentaryType } from '@/hooks/useBitcoinAllocationModels';

interface QuarterlyCommentaryProps {
  commentary: CommentaryType | null;
  quarter: string;
  loading: boolean;
}

export function QuarterlyCommentary({ commentary, quarter, loading }: QuarterlyCommentaryProps) {
  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="flex items-center gap-4 mb-8">
        <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center shadow-lg">
          <Lightbulb className="w-7 h-7 text-white" />
        </div>
        <div>
          <span className="text-xs font-bold text-blue-400 uppercase tracking-wider">Chapter XXIII</span>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground">Quarterly Model Commentary</h2>
        </div>
      </div>

      <motion.div 
        className="p-8 rounded-2xl bg-gradient-to-br from-blue-500/10 to-blue-500/5 border-2 border-blue-500/30"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <p className="text-foreground/90 leading-relaxed text-lg mb-6">
          <strong>{quarter} State:</strong>{' '}
          {commentary?.commentary_text || 'Commentary not available for this quarter.'}
        </p>

        {commentary?.regime_summary && (
          <p className="text-foreground/70 leading-relaxed">
            <strong>Regime classification:</strong>{' '}
            {commentary.regime_summary}
          </p>
        )}
      </motion.div>

      <div className="p-6 rounded-xl bg-muted/30 border border-border/40">
        <p className="text-sm text-foreground/60 italic">
          This commentary is generated by the model's logic layer and describes observed state, not recommended action. The framework does not provide buy, sell, or hold recommendations. All investment decisions remain solely with the user.
        </p>
      </div>
    </div>
  );
}
