
-- Update last_contact_date for all recipients of the "Outreach campagna 2026" campaign sent on 2026-01-14
UPDATE abc_investors 
SET last_contact_date = '2026-01-14 07:32:33+00'
WHERE LOWER(email) IN (
  'roberto.ferraresi@equityclub.eu',
  'igor.calciogaudino@gmail.com',
  'stefano.cassina@quattror.com',
  'm.forasassitorresani@cassiopeapartners.com',
  'rossano.rufini@outlook.com',
  'antongiulio.marti@hoopcapital.it',
  'm.sciano@figc.it',
  'giuseppe.turri@gmail.com',
  'a.picchi@lmdvcapital.it',
  'roberto.ruggeri@varie.net',
  'alessandro.maganza@eni.com',
  'l.martinuzzi@21invest.com',
  'marco.farina@azimut.it',
  'r.roma@romafamilyoffice.com',
  'mario.piredda@mps.it',
  'simone.ruzzante@generali.com',
  'a.reale@fondoitaliano.it',
  'sebastiano.barocco@bnpparibas.com',
  'mara.ariatti@ubs.com',
  'massimiliano.giannone@credit-suisse.com',
  'edoardo.bertini@ubs.com',
  'alessandro.bianchi@mediobanca.com',
  'valeria.santoro@ubs.com',
  'emanuele.bellingeri@ubs.com',
  'giorgio.dipalma@intesasanpaolo.com',
  'e.cibati@cassaforense.it',
  'stefano.gaeta@bper.it',
  'g.sella@sellagroup.eu',
  'l.rovati@rottapharm.com',
  'fabio.iannelli@intesasanpaolo.com',
  'pierre.ricq@ubp.com',
  'g.didio@fondoitaliano.it',
  'edoardo.capuzzi@sella.it',
  'pierpaolo.dalcortivo@allianz.it',
  'i.fissore@bancadelpiemonte.it',
  'yoann.nini@ubs.com',
  'marco.tubia@mediobanca.com',
  'c.decourten@fondoitaliano.it',
  'mauro.festa@mps.it',
  'alessandro.capeccia@fideuram.it',
  'davide.longo@bancainvestis.it',
  'daniele.crepaz@jpmorgan.com',
  'tommaso.righetti@pictet.com',
  'janek.moik@ubs.com',
  'stefano.gratti@bancagenerali.it',
  'michael.brunner@ubs.com',
  'aldo.dibernardo@fondoitaliano.it',
  'concetta.cesarano@mps.it',
  'm.boschetti@familyofficeitalia.com',
  'massimo.depalma@gam.com'
);
